# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FreightInfo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PartitionMetrics(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PartitionMetrics()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPartitionMetrics(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PartitionMetrics
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PartitionMetrics
    def CutNet(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PartitionMetrics
    def Connectivity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PartitionMetrics
    def EdgeCut(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PartitionMetrics
    def VertexCut(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PartitionMetrics
    def Replicas(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PartitionMetrics
    def ReplicationFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PartitionMetrics
    def Balance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def PartitionMetricsStart(builder):
    builder.StartObject(7)

def Start(builder):
    PartitionMetricsStart(builder)

def PartitionMetricsAddCutNet(builder, cutNet):
    builder.PrependFloat64Slot(0, cutNet, 0.0)

def AddCutNet(builder, cutNet):
    PartitionMetricsAddCutNet(builder, cutNet)

def PartitionMetricsAddConnectivity(builder, connectivity):
    builder.PrependFloat64Slot(1, connectivity, 0.0)

def AddConnectivity(builder, connectivity):
    PartitionMetricsAddConnectivity(builder, connectivity)

def PartitionMetricsAddEdgeCut(builder, edgeCut):
    builder.PrependUint64Slot(2, edgeCut, 0)

def AddEdgeCut(builder, edgeCut):
    PartitionMetricsAddEdgeCut(builder, edgeCut)

def PartitionMetricsAddVertexCut(builder, vertexCut):
    builder.PrependUint64Slot(3, vertexCut, 0)

def AddVertexCut(builder, vertexCut):
    PartitionMetricsAddVertexCut(builder, vertexCut)

def PartitionMetricsAddReplicas(builder, replicas):
    builder.PrependUint64Slot(4, replicas, 0)

def AddReplicas(builder, replicas):
    PartitionMetricsAddReplicas(builder, replicas)

def PartitionMetricsAddReplicationFactor(builder, replicationFactor):
    builder.PrependFloat64Slot(5, replicationFactor, 0.0)

def AddReplicationFactor(builder, replicationFactor):
    PartitionMetricsAddReplicationFactor(builder, replicationFactor)

def PartitionMetricsAddBalance(builder, balance):
    builder.PrependFloat64Slot(6, balance, 0.0)

def AddBalance(builder, balance):
    PartitionMetricsAddBalance(builder, balance)

def PartitionMetricsEnd(builder):
    return builder.EndObject()

def End(builder):
    return PartitionMetricsEnd(builder)
